# Generated by Django 6.0.7 on 2026-07-08 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('parsing', 'Parsing'), ('awaiting_approval', 'Awaiting Approval'), ('committed', 'Committed')], default='parsing', max_length=20)),
                ('rows_json', models.JSONField(default=list)),
                ('report_json', models.JSONField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='groups.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('EXACT_DUPLICATE', 'Exact Duplicate'), ('CONFLICTING_DUPLICATE', 'Conflicting Duplicate'), ('THOUSANDS_SEPARATOR', 'Thousands Separator'), ('SUB_UNIT_PRECISION', 'Sub Unit Precision'), ('NAME_NORMALIZATION', 'Name Normalization'), ('NAME_ALIAS_AMBIGUOUS', 'Name Alias Ambiguous'), ('MISSING_PAYER', 'Missing Payer'), ('SETTLEMENT_AS_EXPENSE', 'Settlement As Expense'), ('PERCENTAGE_SUM_INVALID', 'Percentage Sum Invalid'), ('FOREIGN_CURRENCY', 'Foreign Currency'), ('NEGATIVE_AMOUNT_REFUND', 'Negative Amount Refund'), ('NON_MEMBER_PARTICIPANT', 'Non Member Participant'), ('MISSING_CURRENCY', 'Missing Currency'), ('AMBIGUOUS_DATE', 'Ambiguous Date'), ('ZERO_AMOUNT', 'Zero Amount'), ('DEPARTED_MEMBER_IN_SPLIT', 'Departed Member In Split'), ('SPLITTYPE_DETAIL_MISMATCH', 'Splittype Detail Mismatch'), ('OUT_OF_ORDER_ROW', 'Out Of Order Row')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('blocking', 'Blocking')], max_length=10)),
                ('source_row_numbers', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('policy', models.TextField()),
                ('status', models.CharField(choices=[('auto_applied', 'Auto Applied'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='auto_applied', max_length=20)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('resolution_json', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies_resolved', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='importer.importbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
