# Generated by Django 6.0.7 on 2026-07-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='reanalyzed',
            field=models.BooleanField(default=False),
        ),
    ]
